use crate::{memory::map::VRAM_START, ppu::Ppu};

const TILE_DATA_SIGNED_START: u16 = 0x9000;
const BG_TILE_MAP_START: u16 = 0x9800;
const BG_TILE_MAP_ALT_START: u16 = 0x9C00;

const TILE_SIZE: u8 = 8;
const TILES_PER_ROW: u8 = 32;
const TILE_SIZE_BYTES: u16 = 16;
const TILE_MAP_SIZE: u16 = 0x400;

/// Steps performed by the pixel fetcher to obtain one background tile.
#[derive(Clone, Copy)]
enum FetcherStep {
    StartUp,
    TileNumber,
    TileDataLow,
    TileDataHigh,
    Push,
}

/// Request generated by the pixel fetcher.
///
/// The PPU is responsible for executing the request and providing
/// the result back to the fetcher when necessary.
pub(super) enum FetcherRequest {
    ReadVram(u16),
    Push { low: u8, high: u8 },
}

/// Context required to fetch the current tile.
#[derive(Default)]
struct FetcherContext {
    tile_map_address: u16,
    row: u8,
    tile_data_unsigned: bool,
}

/// Pixel fetcher state machine.
///
/// The fetcher obtains the tile number and the two bytes representing
/// the current tile row. Once both bytes have been fetched, the tile
/// is pushed into the pixel FIFO.
///
/// Each timed fetch step takes two T-cycles. The initial startup phase
/// takes six T-cycles and produces no VRAM request.
pub struct Fetcher {
    step: FetcherStep,
    cycles: u8,

    x: u8,

    tile_number: u8,
    tile_data_low: u8,
    tile_data_high: u8,

    context: FetcherContext,
}

impl Fetcher {
    pub fn new() -> Self {
        Self {
            step: FetcherStep::StartUp,
            cycles: 0,

            x: 0,

            tile_number: 0,
            tile_data_low: 0,
            tile_data_high: 0,

            context: FetcherContext::default(),
        }
    }

    pub fn reset(&mut self) {
        self.step = FetcherStep::StartUp;
        self.cycles = 0;

        self.x = 0;

        self.tile_number = 0;
        self.tile_data_low = 0;
        self.tile_data_high = 0;

        self.context = FetcherContext::default();
    }

    /// Updates the context used to fetch the current background tile.
    ///
    /// The PPU provides this information because it depends on PPU state
    /// such as the current scanline, scroll registers, and LCDC settings.
    pub(super) fn add_context(&mut self, tile_map_address: u16, row: u8, tile_data_unsigned: bool) {
        self.context = FetcherContext {
            tile_map_address,
            row,
            tile_data_unsigned,
        };
    }

    /// Returns the number of T-cycles required by the current fetch step.
    fn step_cycles(&self) -> u8 {
        match self.step {
            FetcherStep::StartUp => 6,
            FetcherStep::TileNumber => 2,
            FetcherStep::TileDataLow => 2,
            FetcherStep::TileDataHigh => 2,
            FetcherStep::Push => 0,
        }
    }

    /// Calculates the VRAM address of the tile data for the given tile index.
    fn tile_data_address(&self, tile_index: u8) -> u16 {
        if self.context.tile_data_unsigned {
            let offset = tile_index as u16 * TILE_SIZE_BYTES;
            VRAM_START + offset
        } else {
            let signed_index = tile_index as i8 as i16;
            let offset = signed_index * TILE_SIZE_BYTES as i16;

            (TILE_DATA_SIGNED_START as i16 + offset) as u16
        }
    }

    /// Advances the fetcher by one T-cycle and returns a request when
    /// the current step has completed.
    pub(super) fn tick(&mut self) -> Option<FetcherRequest> {
        self.cycles += 1;

        if self.cycles < self.step_cycles() {
            return None;
        }

        self.cycles = 0;

        match self.step {
            FetcherStep::StartUp => {
                self.step = FetcherStep::TileNumber;
                None
            }

            FetcherStep::TileNumber => {
                Some(FetcherRequest::ReadVram(self.context.tile_map_address))
            }

            FetcherStep::TileDataLow => {
                let tile_address = self.tile_data_address(self.tile_number);

                let row_offset = self.context.row as u16 * 2;

                Some(FetcherRequest::ReadVram(tile_address + row_offset))
            }

            FetcherStep::TileDataHigh => {
                let tile_address = self.tile_data_address(self.tile_number);

                let row_offset = self.context.row as u16 * 2;

                Some(FetcherRequest::ReadVram(tile_address + row_offset + 1))
            }

            FetcherStep::Push => Some(FetcherRequest::Push {
                low: self.tile_data_low,
                high: self.tile_data_high,
            }),
        }
    }

    pub(super) fn receive(&mut self, value: u8) -> Option<FetcherRequest> {
        match self.step {
            FetcherStep::TileNumber => {
                self.tile_number = value;
                self.step = FetcherStep::TileDataLow;
                None
            }

            FetcherStep::TileDataLow => {
                self.tile_data_low = value;
                self.step = FetcherStep::TileDataHigh;
                None
            }

            FetcherStep::TileDataHigh => {
                self.tile_data_high = value;
                self.step = FetcherStep::Push;
                Some(FetcherRequest::Push {
                    low: self.tile_data_low,
                    high: self.tile_data_high,
                })
            }

            FetcherStep::StartUp | FetcherStep::Push => {
                unreachable!("Fetcher cannot receive VRAM data in this step")
            }
        }
    }

    pub(super) fn complete_push(&mut self) {
        self.step = FetcherStep::TileNumber;
        self.x = self.x.wrapping_add(1);
    }
}

impl Ppu {
    /// Returns the base address of the selected background tile map.
    fn bg_tile_map_address(&self) -> u16 {
        if self.is_bg_tile_map() {
            BG_TILE_MAP_ALT_START
        } else {
            BG_TILE_MAP_START
        }
    }

    /// Calculates the tile map offset for the current scanline and
    /// horizontal scroll position.
    fn bg_tile_map_offset(&self) -> u16 {
        let y = self.ly.wrapping_add(self.scy);
        let y_offset = TILES_PER_ROW as u16 * (y / TILE_SIZE) as u16;
        let mut x_offset = self.fetcher.x + self.scx / TILE_SIZE;

        // We keep the X offset between the 32 tiles
        x_offset &= TILES_PER_ROW - 1;

        let tile_map_offset = y_offset + x_offset as u16;

        // We keep the offset between the tile map values
        tile_map_offset & (TILE_MAP_SIZE - 1)
    }

    /// Returns the row within the current tile for the current scanline.
    fn bg_tile_row(&self) -> u8 {
        self.ly.wrapping_add(self.scy) % TILE_SIZE
    }

    /// Provides the fetcher with the context required to fetch the next tile.
    ///
    /// The context is derived from the current PPU state and includes
    /// the selected tile map address, tile row, and tile data addressing mode.
    pub(super) fn add_fetcher_context(&mut self) {
        let tile_map_address = self.bg_tile_map_address() + self.bg_tile_map_offset();

        let row = self.bg_tile_row();
        let tile_data_unsigned = self.is_bg_window_tile_data();

        self.fetcher
            .add_context(tile_map_address, row, tile_data_unsigned);
    }
}
