//! Sprite pixel fetcher for the Game Boy PPU.

use super::sprites::Sprite;

use crate::{memory::map::VRAM_START, ppu::Ppu};

const TILE_SIZE_BYTES: u16 = 16;

const SPRITE_HEIGHT_8X8: u8 = 8;
const SPRITE_HEIGHT_8X16: u8 = 16;

const SPRITE_Y_OFFSET: u8 = 16;

const ATTRIBUTE_Y_FLIP: u8 = 6;

const DEFAULT_CYCLES: u8 = 2;
const NONE_CYCLES: u8 = 0;

/// State of the sprite fetcher.
#[derive(Clone, Copy)]
enum SpriteFetcherStep {
    TileNumber,
    TileDataLow,
    TileDataHigh,
    Push,
}

/// Request generated by the sprite fetcher.
///
/// The PPU is responsible for executing the request and providing
/// the result back to the fetcher when necessary.
pub(super) enum SpriteFetcherRequest {
    ReadVram(u16),
    Push { low: u8, high: u8 },
}

/// Fetches the pixel data for a selected sprite.
///
/// The fetcher obtains the two bytes representing the current sprite
/// row and then exposes them for pixel rendering.
pub(super) struct SpriteFetcher {
    step: SpriteFetcherStep,
    cycles: u8,
    active: bool,

    tile_data_low: u8,
    tile_data_high: u8,

    tile_data_address: u16,

    sprite: Sprite,
}

impl SpriteFetcher {
    pub(super) fn new() -> Self {
        Self {
            step: SpriteFetcherStep::TileNumber,
            cycles: 0,
            active: false,

            tile_data_low: 0,
            tile_data_high: 0,
            tile_data_address: 0,

            sprite: Sprite::default(),
        }
    }

    pub(super) fn is_active(&self) -> bool {
        self.active
    }

    pub(super) fn sprite_x(&self) -> u8 {
        self.sprite.x
    }

    pub(super) fn reset(&mut self) {
        self.step = SpriteFetcherStep::TileNumber;
        self.cycles = 0;
        self.active = false;
        self.tile_data_low = 0;
        self.tile_data_high = 0;
        self.sprite = Sprite::default();
    }

    pub(super) fn add_context(&mut self, sprite: Sprite, ly: u8, sprite_height: u8) {
        self.active = true;

        self.sprite = sprite;
        self.tile_data_address = self.sprite_tile_data_address(ly, sprite_height);
    }

    fn sprite_row_and_tile(&self, ly: u8, sprite_height: u8) -> (u8, u8) {
        let line = ly + SPRITE_Y_OFFSET;

        let mut row = line - self.sprite.y;

        if self.sprite.attributes & (1 << ATTRIBUTE_Y_FLIP) != 0 {
            row = sprite_height - 1 - row;
        }

        let tile = if sprite_height == SPRITE_HEIGHT_8X8 {
            self.sprite.tile
        } else if row < SPRITE_HEIGHT_8X8 {
            self.sprite.tile & !1
        } else {
            self.sprite.tile | 1
        };

        (row % SPRITE_HEIGHT_8X8, tile)
    }

    fn tile_data_address(&self, tile: u8) -> u16 {
        VRAM_START + tile as u16 * TILE_SIZE_BYTES
    }

    fn sprite_tile_data_address(&self, ly: u8, sprite_height: u8) -> u16 {
        let (row, tile) = self.sprite_row_and_tile(ly, sprite_height);

        self.tile_data_address(tile) + row as u16 * 2
    }

    fn step_cycles(&self) -> u8 {
        if let SpriteFetcherStep::Push = self.step {
            return NONE_CYCLES;
        }
        DEFAULT_CYCLES
    }

    fn execute_step(&mut self) -> Option<SpriteFetcherRequest> {
        match self.step {
            SpriteFetcherStep::TileNumber => {
                self.step = SpriteFetcherStep::TileDataLow;
                None
            }
            SpriteFetcherStep::TileDataLow => {
                Some(SpriteFetcherRequest::ReadVram(self.tile_data_address))
            }

            SpriteFetcherStep::TileDataHigh => {
                Some(SpriteFetcherRequest::ReadVram(self.tile_data_address + 1))
            }

            SpriteFetcherStep::Push => Some(SpriteFetcherRequest::Push {
                low: self.tile_data_low,
                high: self.tile_data_high,
            }),
        }
    }

    pub(super) fn tick(&mut self) -> Option<SpriteFetcherRequest> {
        self.cycles += 1;

        if self.cycles < self.step_cycles() {
            return None;
        }

        self.cycles = 0;
        self.execute_step()
    }

    pub(super) fn receive(&mut self, value: u8) {
        match self.step {
            SpriteFetcherStep::TileDataLow => {
                self.tile_data_low = value;
                self.step = SpriteFetcherStep::TileDataHigh
            }
            SpriteFetcherStep::TileDataHigh => {
                self.tile_data_high = value;
                self.step = SpriteFetcherStep::Push;
            }
            SpriteFetcherStep::TileNumber | SpriteFetcherStep::Push => {
                unreachable!("Fetcher cannot receive VRAM data in this step")
            }
        }
    }

    pub(super) fn complete_push(&mut self) {
        self.step = SpriteFetcherStep::TileNumber;
        self.cycles = 0;
        self.active = false;
    }
}

impl Ppu {
    /// Checks whether the next sprite should be fetched at the current drawing position.
    ///
    /// The X coordinate stored in OAM is offset by 8 pixels from the sprite's
    /// screen position, so the fetch starts when the OAM X coordinate reaches
    /// `drawing_x + 8`.
    ///
    /// Returns `Some` if the next sprite should be fetched, or `None` otherwise.
    fn should_fetch_sprite(&self) -> Option<Sprite> {
        self.sprites
            .get(self.sprite_fetch_index)
            .copied()
            .filter(|sprite| sprite.x <= self.drawing_x + 8)
    }

    pub(super) fn update_sprite_fetcher_context(&mut self) {
        if let Some(sprite) = self.should_fetch_sprite() {
            let sprite_height = if self.is_obj_size() {
                SPRITE_HEIGHT_8X16
            } else {
                SPRITE_HEIGHT_8X8
            };

            self.sprite_fetch_index += 1;
            self.sprite_fetcher
                .add_context(sprite, self.ly, sprite_height);
        }
    }
}
